name: Social Texting
version: 1.0.0
main: com.example.socialtexting.SocialTextingPlugin
api-version: 1.21
commands:
  st:
    description: Команда модерации ST
    usage: /st [rus|eng] [nick] [reason] [num]/[msg]
